#ifndef DIRCON_H
#define DIRCON_H

#include <Arduino.h>
#include <NimBLEDevice.h>

#define DIRCON_MDNS_SERVICE_NAME "_wahoo-fitness-tnp"
#define DIRCON_MDNS_SERVICE_PROTOCOL "tcp"

#define DIRCON_CHAR_PROP_FLAG_READ 0x01
#define DIRCON_CHAR_PROP_FLAG_WRITE 0x02
#define DIRCON_CHAR_PROP_FLAG_NOTIFY 0x04
#define DIRCON_MSGID_ERROR 0xFF
#define DIRCON_MSGID_DISCOVER_SERVICES 0x01
#define DIRCON_MSGID_DISCOVER_CHARACTERISTICS 0x02
#define DIRCON_MSGID_READ_CHARACTERISTIC 0x03
#define DIRCON_MSGID_WRITE_CHARACTERISTIC 0x04
#define DIRCON_MSGID_ENABLE_CHARACTERISTIC_NOTIFICATIONS 0x05
#define DIRCON_MSGID_UNSOLICITED_CHARACTERISTIC_NOTIFICATION 0x06
#define DIRCON_RESPCODE_SUCCESS_REQUEST 0x00
#define DIRCON_RESPCODE_UNKNOWN_MESSAGE_TYPE 0x01
#define DIRCON_RESPCODE_UNEXPECTED_ERROR 0x02
#define DIRCON_RESPCODE_SERVICE_NOT_FOUND 0x03
#define DIRCON_RESPCODE_CHARACTERISTIC_NOT_FOUND 0x04
#define DIRCON_RESPCODE_CHARACTERISTIC_OPERATION_NOT_SUPPORTED 0x05
#define DIRCON_RESPCODE_CHARACTERISTIC_WRITE_FAILED 0x06
#define DIRCON_RESPCODE_UNKNOWN_PROTOCOL 0x07

std::vector<uint8_t> generateDirConPacket(uint8_t messageVersion, uint8_t identifier, uint8_t sequenceNumber, uint8_t responseCode, BLEUUID uuid, std::vector<uint8_t> data);

#endif